// SEO landing-page content per occasion. Kept separate from occasions.js
// (which drives in-app card styling) because this is copy for Google/crawlers,
// not runtime UI config — different concern, different lifecycle.
//
// Each page has:
//   - title / metaDescription / h1 / intro  → what Google shows and reads first
//   - wishGroups                            → ready-to-copy wishes, grouped by who they're for.
//                                             People searching "marriage wishes" or "birthday wishes"
//                                             want text they can copy, so this is the main content.
//
// NOTE: the object KEYS (birthday, newhome, …) are also stored in the database as each card's
// occasionType, so never rename a key — only change `path`.

export const SEO_PAGES = {
  birthday: {
    path: '/birthday-wishes',
    title: 'Free Birthday Wishes Generator — Create an AI Birthday Card Online',
    metaDescription: 'Copy 30+ birthday wishes for friends, family and loved ones, or create a free AI birthday card with your photo, animations and a shareable link.',
    h1: 'Free Birthday Wishes Generator',
    wishesHeading: 'Birthday Wishes You Can Copy',
    intro: `Looking for the perfect birthday wishes for someone special? Copy a ready-made wish below, or use our free birthday wishes generator to create a personalized, animated birthday card in seconds. Just add the recipient's name, your relationship to them, and an optional photo — our AI writes a heartfelt, relationship-aware birthday message for you, or you can write your own. Every card comes with animations, music, and a shareable link you can send over WhatsApp, Instagram, or email.`,
    wishGroups: [
      { heading: 'Birthday Wishes for a Friend', wishes: [
        "Happy Birthday to the friend who makes every ordinary day feel like a party. Never change!",
        "Another year older, but you're still the person I laugh with the most. Have an amazing day!",
        "Thank you for being there through every high and low. I hope your birthday is as wonderful as you are.",
        "Cheers to you on your birthday! May this year bring you more adventures, more laughter, and fewer Mondays.",
        "Some friends are for a season, but you're for life. Happy Birthday, and here's to many more years of friendship.",
        "Today is all about you. Eat the cake, enjoy the attention, and know how loved you are. Happy Birthday!",
      ]},
      { heading: 'Birthday Wishes for a Brother or Sister', wishes: [
        "Happy Birthday to my first friend and forever partner in crime. Growing up with you was the best part.",
        "Happy Birthday to the one who knows all my secrets and still likes me. Love you loads!",
        "No matter how old we get, you'll always be the one I turn to first. Wishing you a joyful birthday!",
        "Happy Birthday! Thank you for the memories, the fights we laughed about later, and the support I can always count on.",
        "To my sibling, my protector and my friend: may this birthday bring you everything you've worked so hard for.",
        "I'm so lucky to have a sibling like you. Have a birthday full of cake, comfort and all your favourite things.",
      ]},
      { heading: 'Birthday Wishes for Mom or Dad', wishes: [
        "Happy Birthday, Mom! Everything good in me began with your love. Today is all about you.",
        "Dad, you've been my strength and my role model. Wishing you good health and happiness on your birthday.",
        "Thank you for every sacrifice, every piece of advice, and every hug. Happy Birthday to the best mother in the world.",
        "May you be blessed with a long life, good health and a heart full of joy. Happy Birthday, Dad!",
        "Mom, no gift could ever say thank you enough. I love you more than words can say. Happy Birthday!",
        "To the person who taught me to be strong and kind: happy birthday. I'm proud to be your child.",
      ]},
      { heading: 'Birthday Wishes for Wife, Husband or Partner', wishes: [
        "Happy Birthday to the love of my life. Every day with you is a gift, and today I get to celebrate you.",
        "You make my world brighter just by being in it. Wishing you a birthday as beautiful as your heart.",
        "Another year of you, another year of my luckiest moments. I love you more every day. Happy Birthday!",
        "To my best friend and my forever person: thank you for loving me the way you do. Happy Birthday!",
        "May all your wishes come true today, and if one is missing, I'll do my best to make it happen. Happy Birthday, my love.",
        "Growing old with you is the plan, and every birthday makes me more excited for what's next. I love you.",
      ]},
      { heading: 'Birthday Wishes for a Son or Daughter', wishes: [
        "Happy Birthday to my little star! Watching you grow is my greatest joy. Never stop dreaming big.",
        "You make me proud every single day. Wishing you a birthday filled with laughter, cake and surprises.",
        "From the day you were born, you've filled our home with love. Happy Birthday, my darling child!",
        "May this year bring you courage, curiosity and all the happiness you deserve. We love you endlessly.",
        "Happy Birthday to a wonderful son! Keep being kind, keep working hard, and know we're always behind you.",
        "Happy Birthday to a wonderful daughter! You're growing into an amazing person, and we couldn't be prouder.",
      ]},
    ],
  },
  anniversary: {
    path: '/anniversary-wishes',
    title: 'Free Anniversary Wishes Generator — Create an AI Anniversary Card Online',
    metaDescription: 'Copy 30+ anniversary wishes for your husband, wife, parents or friends, or create a free AI anniversary card with a photo and a shareable link.',
    h1: 'Free Anniversary Wishes Generator',
    wishesHeading: 'Anniversary Wishes You Can Copy',
    intro: `Celebrate love with free, personalized anniversary wishes. Copy a ready-made message below, or let our generator create an animated anniversary card with a heartfelt AI-written message tailored to your relationship — whether it's for a spouse, parents, or friends celebrating their special day. Add a photo, choose a template, and share the card instantly with a link.`,
    wishGroups: [
      { heading: 'Anniversary Wishes for Husband', wishes: [
        "Happy Anniversary, my love. Every year with you has been better than the last, and I'd choose you again in a heartbeat.",
        "Thank you for being my partner, my comfort and my best friend. Here's to many more years together.",
        "Loving you is the easiest thing I've ever done. Happy Anniversary to my favourite person.",
        "Through every season of life, your hand in mine has made me feel at home. Happy Anniversary, husband.",
        "You still give me butterflies after all these years. Happy Anniversary, and thank you for everything.",
        "Cheers to us, to the memories we've made and the ones still waiting. I love you always.",
      ]},
      { heading: 'Anniversary Wishes for Wife', wishes: [
        "Happy Anniversary to the woman who makes life beautiful. Thank you for your love, patience and endless support.",
        "You're my greatest blessing. I fall in love with you a little more every year. Happy Anniversary, my wife.",
        "Thank you for building a home full of love with me. Happy Anniversary, and here's to forever.",
        "Every good memory I have has you in it. Wishing us many more years of laughter and love.",
        "You're the reason I believe in true love. Happy Anniversary, my heart.",
        "After all these years, you're still the one I want to come home to. I love you more than ever.",
      ]},
      { heading: 'Anniversary Wishes for Parents', wishes: [
        "Happy Anniversary, Mom and Dad! Your love has been the example our whole family looks up to.",
        "Thank you for showing us what true partnership looks like. Wishing you many more years of togetherness.",
        "Your love story is the reason our home is so full of warmth. Happy Anniversary to the best parents ever!",
        "May your bond grow stronger with every passing year. Sending you all my love on your special day.",
        "Through good times and hard times, you stood by each other. That's the best lesson you've ever taught me.",
        "Wishing you both health, happiness and many more years of loving each other. Happy Anniversary!",
      ]},
      { heading: 'Anniversary Wishes for Friends and Couples', wishes: [
        "Happy Anniversary to a couple who makes love look easy. Wishing you many more years of happiness.",
        "You two are proof that great love exists. Congratulations on another wonderful year together!",
        "Cheers to you both on your anniversary! May your days stay full of laughter and your hearts full of love.",
        "It's a joy to see how you support each other. Happy Anniversary, and here's to many more.",
        "Two great people, one great love story. Happy Anniversary to my favourite couple!",
        "Wishing you a day as special as the bond you share. Happy Anniversary!",
      ]},
      { heading: 'Anniversary Wishes for Boyfriend or Girlfriend', wishes: [
        "Happy Anniversary, my love. Meeting you was the best thing that ever happened to me.",
        "Every day with you feels like a new adventure. Thank you for loving me. Happy Anniversary!",
        "Even when we're miles apart, you're always close to my heart. Happy Anniversary, and I can't wait to see you.",
        "Thank you for choosing me every single day. I'm so grateful for us. Happy Anniversary!",
        "One more year of memories, and I'm already excited for the next. I love you so much.",
        "You turned my ordinary days into my favourite ones. Happy Anniversary to my partner in everything.",
      ]},
    ],
  },
  wedding: {
    path: '/wedding-wishes',
    title: 'Wedding Wishes & Marriage Wishes — Free AI Wedding Card Maker',
    metaDescription: 'Copy 30+ wedding wishes and marriage wishes for the bride and groom, friends and family, or create a free AI wedding card with a photo and a shareable link.',
    h1: 'Free Wedding & Marriage Wishes Generator',
    wishesHeading: 'Wedding Wishes and Marriage Wishes You Can Copy',
    intro: `Find the right words for a wedding. Copy a ready-made wedding wish or marriage wish below for the bride and groom, a friend, a sibling or your own son or daughter — or use our free generator to create an animated wedding card with a heartfelt AI-written message. Add a photo, pick a template, and share the card with the happy couple through one link on WhatsApp, Instagram or email.`,
    wishGroups: [
      { heading: 'Wedding Wishes for the Bride and Groom', wishes: [
        "Congratulations on your wedding! May your marriage be filled with love, laughter and a lifetime of happiness.",
        "Wishing you a beautiful beginning to your life together. May every day bring you closer.",
        "Two hearts, one journey. Congratulations to the newlyweds, and may your love grow stronger each year.",
        "May your home be full of joy and your hearts full of love. Happy Wedding Day!",
        "Here's to a marriage built on trust, kindness and plenty of laughter. Congratulations!",
        "Today you become one family. Wishing you endless love, patience and happiness in your new life together.",
      ]},
      { heading: 'Marriage Wishes for a Friend', wishes: [
        "I'm so happy for you! You deserve all the love in the world. Congratulations on your wedding, my friend.",
        "Seeing you find your person is the best feeling. Wishing you a lifetime of love and adventure.",
        "Congratulations! May your marriage be as wonderful as your friendship has been to me.",
        "Today is the start of your greatest chapter. Thank you for letting me be part of it. Best wishes!",
        "Wishing you and your partner a lifetime of love, respect and happy surprises. Congratulations on your big day!",
        "You look happier than ever, and I couldn't be more thrilled. Happy Wedding Day!",
      ]},
      { heading: 'Wedding Wishes for a Brother or Sister', wishes: [
        "It's so special to see you begin this new journey. Wishing you a lifetime of love.",
        "Congratulations on your wedding! Welcome to the family, and may you both be blessed with happiness.",
        "From childhood games to your wedding day, what a journey! I'm so proud of you. Love you always.",
        "I couldn't have picked a better partner for you. Wishing you both endless joy in your marriage.",
        "May your new home be filled with love, and may you never stop laughing together. Happy Wedding Day!",
        "Today I'm gaining a new family member and watching my favourite person be happy. Congratulations!",
      ]},
      { heading: 'Marriage Wishes for Your Son or Daughter', wishes: [
        "Today our hearts are full. May your marriage be blessed with love, understanding and happiness. We're so proud of you.",
        "Watching you begin this new chapter makes us so happy. Wishing you both a lifetime of togetherness.",
        "May you always support each other, listen to each other and laugh together. Congratulations, our dear child.",
        "We welcome your partner with open arms. Wishing you both a beautiful, blessed married life.",
        "You've always brought us joy, and today even more. May your marriage be blessed with love and peace.",
        "Our love and blessings are always with you both. Happy Wedding Day!",
      ]},
      { heading: 'Short Marriage Wishes for a Card', wishes: [
        "Congratulations on your marriage!",
        "Wishing you a lifetime of love and happiness.",
        "Happy Wedding Day! May your love story be a long one.",
        "Best wishes for a beautiful married life.",
        "Cheers to the happy couple!",
        "May your marriage be blessed with joy, love and laughter.",
      ]},
    ],
  },
  graduation: {
    path: '/graduation-wishes',
    title: 'Free Graduation Wishes Generator — Create an AI Congratulations Card',
    metaDescription: 'Copy 30+ graduation wishes for a son, daughter, friend or sibling, or create a free AI graduation card with a photo, animations and a shareable link.',
    h1: 'Free Graduation Wishes Generator',
    wishesHeading: 'Graduation Wishes You Can Copy',
    intro: `Congratulate a graduate with the right words. Copy a ready-made graduation wish below, or create a free, personalized graduation card. Our AI writes a proud, encouraging message based on your relationship with the graduate, and you can add their photo, pick a celebration template, and share it instantly.`,
    wishGroups: [
      { heading: 'Graduation Wishes for a Son or Daughter', wishes: [
        "We're so proud of you! Your hard work has paid off. Congratulations, graduate!",
        "You did it, and we couldn't be prouder. Wishing you great things in the chapter ahead.",
        "Congratulations on your graduation! Follow your dreams, and remember we're always cheering for you.",
        "Every late night and every exam led to this moment. Well done, our dear child!",
        "Today we celebrate your success and can't wait to see what you do next. Congratulations!",
        "You've made our family so proud. May your degree open every door you hope for.",
      ]},
      { heading: 'Graduation Wishes for a Friend', wishes: [
        "Congratulations, graduate! You worked so hard for this and you've earned every bit of the celebration.",
        "We survived the exams and the deadlines. Here's to us, and to the great things ahead. Congratulations!",
        "So happy for you! Your dedication has always inspired me. Wishing you a bright future.",
        "You did it! Now go out there and show the world what you've got. Congratulations on graduating!",
        "Proud of you for never giving up. The best is yet to come. Happy Graduation!",
        "Congratulations to my friend on this huge achievement. Let's celebrate soon!",
      ]},
      { heading: 'Graduation Wishes for a Brother or Sister', wishes: [
        "Congratulations, graduate! I always knew you'd make it. So proud to be your sibling.",
        "You worked hard and it shows. Wishing you every success in whatever comes next.",
        "Watching you graduate is one of my proudest moments. Congratulations on your amazing achievement!",
        "Congratulations on getting your degree! Time to celebrate, and dinner is on you!",
        "You've made the whole family proud. Go chase your dreams, and I'll cheer the loudest.",
        "Way to go, graduate! The world is lucky to get you.",
      ]},
      { heading: 'College and University Graduation Wishes', wishes: [
        "Congratulations on earning your degree. May your knowledge and determination take you far.",
        "Your graduation marks the end of one journey and the start of another. Best wishes for what lies ahead.",
        "Well done on this remarkable achievement. Wishing you success in your career and in life.",
        "Graduation is not an ending but a beginning. Congratulations, and best of luck!",
        "Your effort, discipline and curiosity have brought you here. Congratulations on your graduation.",
        "May your degree be the first of many achievements. Congratulations, graduate!",
      ]},
      { heading: 'Short Graduation Wishes for a Card', wishes: [
        "Congratulations, graduate!",
        "You did it! So proud of you.",
        "Cheers to the graduating class!",
        "Hard work pays off. Congratulations!",
        "Congratulations on your graduation! The future is yours.",
        "Well done, graduate. Go change the world.",
      ]},
    ],
  },
  newjob: {
    path: '/new-job-wishes',
    title: 'Free New Job Wishes Generator — Create an AI Congratulations Card',
    metaDescription: 'Copy 30+ new job wishes and promotion wishes for friends, colleagues and family, or create a free AI congratulations card with a shareable link.',
    h1: 'Free New Job Wishes Generator',
    wishesHeading: 'New Job Wishes You Can Copy',
    intro: `Celebrate someone's new job or career milestone. Copy a ready-made new job wish below, or create a free personalized card. Our AI generates a motivating, excited message for their new chapter, and you can add a photo and share the card with a single link.`,
    wishGroups: [
      { heading: 'New Job Wishes for a Friend', wishes: [
        "Congratulations on the new job! You've earned it, and I can't wait to hear how it goes.",
        "So happy for you! They're lucky to have you. Wishing you a fantastic start.",
        "New job, new adventures. Go show them what you're made of. Congratulations, my friend!",
        "You worked so hard for this opportunity. Congratulations, and let's celebrate soon!",
        "Here's to new beginnings! Wishing you success, great colleagues and a good salary. Congrats!",
        "I always knew you'd land something amazing. Congratulations on your new role!",
      ]},
      { heading: 'New Job Wishes for a Colleague', wishes: [
        "Congratulations on your new role! It's been a pleasure working with you, and I wish you every success.",
        "We'll miss you, but we're so happy for you. Best of luck in your new job!",
        "Your talent and hard work will shine wherever you go. Congratulations on the new opportunity.",
        "Wishing you all the best as you take on this exciting new challenge. Stay in touch!",
        "Congratulations! Your new team is getting a great person. All the best.",
        "Thank you for everything you taught us. Best wishes on your new career step.",
      ]},
      { heading: 'New Job Wishes for a Partner', wishes: [
        "I'm so proud of you! You deserve this new job. Congratulations, my love.",
        "Your hard work finally paid off. I'm so happy for you. Let's celebrate tonight!",
        "New job, new chapter. I'm cheering for you every step of the way.",
        "You're going to do amazing things in this role. I believe in you completely. Congratulations!",
        "Congratulations on the new job! Thank you for working so hard for our future.",
        "I couldn't be prouder. Go get them, and don't forget to enjoy it. Love you!",
      ]},
      { heading: 'First Job Wishes for a Son or Daughter', wishes: [
        "Congratulations on your first job! We're proud of the person you've become.",
        "Your first job is a big step. Work hard, stay curious, and learn something new every day.",
        "So proud of you for landing this role. Wishing you a wonderful start to your career.",
        "You've worked so hard for this moment. Congratulations, and remember we're always here for you.",
        "A new job means new lessons and new friends. Enjoy every bit of it, dear child!",
        "From school days to your first job, we've watched you grow. Congratulations, and best wishes!",
      ]},
      { heading: 'Promotion Wishes', wishes: [
        "Congratulations on your promotion! It's well deserved after all your hard work.",
        "Wishing you continued success in your new position. You've earned every bit of it.",
        "Your dedication has paid off. Congratulations on the promotion!",
        "A big step forward for a big talent. Congratulations on the new title!",
        "Well done on your promotion! May this be the first of many achievements ahead.",
        "So happy to see your hard work recognised. Congratulations on your well-earned promotion!",
      ]},
    ],
  },
  newhome: {
    path: '/housewarming-wishes',
    title: 'Housewarming Wishes & New Home Wishes — Free AI Card Maker',
    metaDescription: 'Copy 30+ housewarming wishes, new home wishes and Griha Pravesh wishes, or create a free AI housewarming card with a photo and a shareable link.',
    h1: 'Free Housewarming & New Home Wishes Generator',
    wishesHeading: 'Housewarming Wishes and New Home Wishes You Can Copy',
    intro: `Welcome someone to their new home with the right words. Copy a ready-made housewarming wish, new home wish or Griha Pravesh wish below, or create a free, personalized housewarming card. Our AI writes a warm, joyful message for their new beginning, complete with animations and a shareable link.`,
    wishGroups: [
      { heading: 'Housewarming Wishes for a Friend', wishes: [
        "Congratulations on your new home! May it be filled with love, laughter and great memories.",
        "Wishing you happiness in every room of your new place. Can't wait for the housewarming party!",
        "A new home is a new beginning. So happy for you, my friend!",
        "May your new home always feel warm, welcoming and full of good friends. Congratulations!",
        "You've made your dream come true. Congratulations on the new house!",
        "Home is where your story continues. Wishing you countless happy days in yours.",
      ]},
      { heading: 'New Home Wishes for Family', wishes: [
        "Welcome to your new home! May it be blessed with peace, health and happiness.",
        "We're so happy to see you settled in your own place. Wishing your family joy and prosperity.",
        "May every corner of your new home be filled with love and blessings. Congratulations to you all!",
        "A house is built with walls, but a home is built with love. Wishing you plenty of both!",
        "Your new home is a place for new memories. May they all be happy ones.",
        "So proud of everything you've worked for. Enjoy your beautiful new home, dear family.",
      ]},
      { heading: 'New Home Wishes for a Neighbour or Colleague', wishes: [
        "Welcome to the neighbourhood! We're so glad you're here. Let us know if you need anything.",
        "Congratulations on your new home! Wishing you a smooth move and a warm welcome.",
        "Happy housewarming! May your new place bring you comfort and joy.",
        "Congratulations on your new house. Wishing you many happy years there.",
        "Best wishes as you settle into your new home. It's a great step!",
        "Enjoy your new home! Wishing you peace, comfort and good times ahead.",
      ]},
      { heading: 'First Home Wishes', wishes: [
        "Your first home! What an achievement. Congratulations, you've earned every brick of it.",
        "Congratulations on your first home. May it be the start of many wonderful memories.",
        "All your hard work and saving has led to this moment. Wishing you happiness in your own place.",
        "Your very own place at last! May it bring you independence, comfort and joy.",
        "First keys, first home, first of many dreams coming true. Congratulations!",
        "Wishing you a home full of love, laughter and good food. Congratulations on your first house!",
      ]},
      { heading: 'Griha Pravesh Wishes', wishes: [
        "Wishing you a blessed Griha Pravesh. May your new home bring peace and prosperity.",
        "Congratulations on your Griha Pravesh! May God's blessings stay with your family always.",
        "May your new home be filled with positivity, good health and endless happiness. Happy Griha Pravesh!",
        "On this auspicious day, we pray for your family's happiness and success in your new home.",
        "May the light of this new beginning fill your home with warmth. Congratulations on your Griha Pravesh!",
        "Wishing you and your family a lifetime of blessings in your beautiful new home.",
      ]},
    ],
  },
  babyshower: {
    path: '/baby-shower-wishes',
    title: 'Free Baby Shower Wishes Generator — Create an AI Baby Shower Card',
    metaDescription: 'Copy 30+ baby shower wishes and new baby wishes for parents-to-be, friends and family, or create a free AI baby shower card with a shareable link.',
    h1: 'Free Baby Shower Wishes Generator',
    wishesHeading: 'Baby Shower Wishes You Can Copy',
    intro: `Celebrate a new little arrival. Copy a ready-made baby shower wish below, or create a free, personalized card. Our AI writes a tender, joyful message for the parents-to-be, and you can add a photo and share the card instantly.`,
    wishGroups: [
      { heading: 'Baby Shower Wishes for the Mom-to-Be', wishes: [
        "You're glowing, and we can't wait to meet your little one. Wishing you a healthy, happy pregnancy.",
        "Congratulations, mama-to-be! Motherhood suits you already. Sending love and good wishes.",
        "Wishing you a smooth delivery and a healthy baby. You're going to be a wonderful mother.",
        "Rest, relax and enjoy every moment of this special time. Congratulations on your baby shower!",
        "May your days ahead be filled with tiny toes, sweet cuddles and pure joy.",
        "Can't wait to celebrate you and your little miracle. Congratulations, mom-to-be!",
      ]},
      { heading: 'Wishes for the Parents-to-Be', wishes: [
        "Congratulations to the soon-to-be parents! Your family is about to grow and so is your love.",
        "Wishing you both endless joy as you get ready to welcome your baby.",
        "A new adventure awaits you. May parenthood bring you everything you dream of.",
        "You two will make amazing parents. Wishing you a healthy baby and a happy home.",
        "Get ready for the best chapter yet. Congratulations on the exciting news!",
        "May your baby's arrival fill your home with laughter, love and a few sleepless but beautiful nights.",
      ]},
      { heading: 'Baby Shower Wishes for a Friend', wishes: [
        "I'm so happy for you! You're going to be a fantastic parent. Congratulations on your baby shower.",
        "Watching you become a parent is such a joy. Sending love to you and the little one.",
        "Can't wait to meet the newest member of the gang. Congratulations, my friend!",
        "Wishing you a healthy baby and a whole lot of rest. Congratulations on your baby shower!",
        "Your baby is so lucky to have you. Wishing you love and laughter in this new chapter.",
        "Congratulations! Get ready for the best hugs of your life.",
      ]},
      { heading: 'Baby Shower Wishes for a Sister or Family Member', wishes: [
        "I'm so excited to become an aunt or uncle! Congratulations, and I'll be there for anything you need.",
        "Wishing you a safe, healthy delivery and a lifetime of happiness with your baby.",
        "Our family is growing, and my heart is full. Congratulations to you both!",
        "Congratulations! Your little one will be surrounded by so much love from all of us.",
        "You've always been my role model, and I know you'll be an amazing parent.",
        "Sending all my blessings for you and your baby. Can't wait for the big day!",
      ]},
      { heading: 'New Baby Wishes', wishes: [
        "Welcome to the world, little one! May your life be full of joy, health and love.",
        "Congratulations on your new arrival! Your family is now complete in the best way.",
        "A new baby is a little bundle of joy. Wishing you many happy days ahead.",
        "Sending love and blessings to your family. Welcome, sweet baby!",
        "Congratulations! May your baby grow up healthy, happy and loved.",
        "Your baby is a gift. Congratulations to the proud new parents!",
      ]},
    ],
  },
  engagement: {
    path: '/engagement-wishes',
    title: 'Free Engagement Wishes Generator — Create an AI Congratulations Card',
    metaDescription: 'Copy 30+ engagement wishes for the happy couple, friends and family, or create a free AI engagement card with a photo and a shareable link.',
    h1: 'Free Engagement Wishes Generator',
    wishesHeading: 'Engagement Wishes You Can Copy',
    intro: `Celebrate an engagement with the right words. Copy a ready-made engagement wish below, or create a free, personalized card. Our AI writes a romantic, joyful message for the couple's new journey together, and you can add a photo and share it with one link.`,
    wishGroups: [
      { heading: 'Engagement Wishes for the Couple', wishes: [
        "Congratulations on your engagement! Wishing you both a lifetime of love and happiness.",
        "Two hearts, one future. May your love keep growing as you begin this new chapter.",
        "Congratulations to the happy couple! May every day bring you closer together.",
        "You two are perfect together. Wishing you the best on this exciting new journey.",
        "May your engagement be the start of the most beautiful chapter of your lives.",
        "Wishing you a joyful engagement and a wonderful wedding to come. Congratulations!",
      ]},
      { heading: 'Engagement Wishes for a Friend', wishes: [
        "I'm so excited for you! Congratulations on your engagement, and I can't wait for the wedding.",
        "You found your person, and I couldn't be happier. Congratulations, my friend!",
        "Congratulations on your engagement! Love looks amazing on you.",
        "So happy for both of you. Let's celebrate soon!",
        "Best wishes to you and your partner. You've earned all this happiness.",
        "Yes! Finally! Congratulations on your engagement. I can't wait to see what's next.",
      ]},
      { heading: 'Engagement Wishes for a Brother or Sister', wishes: [
        "I'm so proud of you. Wishing you and your partner endless love. Congratulations on the engagement!",
        "My favourite person is getting engaged! Congratulations. Count on me for everything.",
        "Your partner is lucky to have you, and you're lucky to have each other. Congratulations!",
        "Congratulations on the engagement! I can't wait to celebrate at the wedding.",
        "Watching you fall in love has been wonderful. Wishing you a happy future together.",
        "Welcome to the family! Congratulations on your engagement to my amazing sibling.",
      ]},
      { heading: 'Engagement Wishes for a Son or Daughter', wishes: [
        "Congratulations on your engagement! We're so happy for you and love your partner already.",
        "Our best wishes are with you both. May your love grow stronger every day.",
        "We're thrilled about your engagement. Wishing you a beautiful life together.",
        "You've always made us proud. Your engagement is one more happy moment. God bless you both.",
        "We couldn't be happier. Congratulations to you and your partner!",
        "May your engagement bring you both endless joy. We're always here for you.",
      ]},
      { heading: 'Short Engagement Wishes for a Card', wishes: [
        "Congratulations on your engagement!",
        "Wishing you a lifetime of love.",
        "Best wishes to the happy couple!",
        "So happy for you both.",
        "Cheers to love and new beginnings!",
        "Congratulations! May your love story be a long one.",
      ]},
    ],
  },
}

export const SEO_PAGE_LIST = Object.entries(SEO_PAGES).map(([key, data]) => ({ key, ...data }))

// Old URLs that must keep working (bookmarks, links already shared, pages Google may have
// already indexed). vercel.json sends a real 301 redirect for these; App.jsx also redirects
// client-side as a fallback for local dev.
export const LEGACY_REDIRECTS = {
  '/new-home-wishes': '/housewarming-wishes',
}
